// <auto-generated />
namespace Amigurumis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Altera_Campo_Foro_para_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altera_Campo_Foro_para_string));
        
        string IMigrationMetadata.Id
        {
            get { return "202009090350184_Altera_Campo_Foro_para_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
