// <auto-generated />
namespace Amigurumis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class muda_campoimagem_para_byte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(muda_campoimagem_para_byte));
        
        string IMigrationMetadata.Id
        {
            get { return "202009160238291_muda_campo-imagem_para_byte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
